### ISSUE TITLE
Plugin completely broken since the last update

### ISSUE THREAD

**Issue by BenBornschein** [toolstack/gp-auto-extract#10]
The plugin no longer works without any error message. Links for editing and extracting no longer work.

**Comment by BenBornschein** [comment]
It looks like the asset files are missing:

![CleanShot 2024-11-05 at 13 59 37@2x](https://github.com/user-attachments/assets/8173f2c5-5fd1-463a-983a-25e3c5f68566)

**Comment by toolstack** [comment]
I moved to a GitHub action for this release, it probably excluded that directory by accident  Will  fix it and do another release later today.

**Comment by toolstack** [comment]
New release published to address issue.
