### ISSUE TITLE
Remove create_function() for php8

### ISSUE THREAD

**Issue by pkolmann** [toolstack/gp-auto-extract#6]
Hi,

you use the depreciated function create_function() (https://www.php.net/manual/en/function.create-function.php) which has been removed for php8.0.

Please replace this with anonymous function calls:

https://www.php.net/manual/en/functions.anonymous.php

**Comment by toolstack** [comment]
Will take a look and update it, should be an easy fix.

**Comment by toolstack** [comment]
Version 0.9 should resolve this now.
