### ISSUE TITLE
new strings added But can’t find them

### ISSUE THREAD

**Issue by ipajen** [toolstack/gp-auto-extract#8]
Using main code as it’s not possible or to edit in 0.9 version. 

1. created a new project “gp-auto-extract” with no other information in GlotPress
2. Used gp-auto-extract on GitHub
3. Extract and following was found.

47 new strings added, 0 updated, 0 fuzzied, and 0 obsoleted in the "gp-auto-extract" project.

But I can’t see them in GlotPress?  Seems they not been added or I am missing something here. First time I using this plugin. Thank you 🙏

**Comment by toolstack** [comment]
Have you setup any locales for the project yet?  gp-auto-extract pulls the originals so if there are not locales there is no visible change.

**Comment by ipajen** [comment]
That was the issue. Thanks for the help. Just learning both GlotPress and GP Auto Extract
