### ISSUE TITLE
PHP Fatal error:  Cannot redeclare get_file_description()

### ISSUE THREAD

**Issue by ipajen** [toolstack/gp-auto-extract#9]
Using main.

After activating the gp-auto-extract plugin I go to the Project Actions menu in GlotPress.
When i click on Auto Extract, I Get There has been a critical error on this website.

from debugs logs:
`PHP Fatal error:  Cannot redeclare get_file_description() (previously declared in /public_html/blog/wp-admin/includes/file.php:80) in /public_html/blog/wp-admin/includes/file.php on line 80`

**Comment by toolstack** [comment]
Most likely caused by another plugin loading the `file.php` code, I'll update the include to an include_once to avoid this.

**Comment by ipajen** [comment]
Using the 1.0 version
Now it gives this instead:

```
`Fatal error: Uncaught Error: array_key_exists(): Argument #2 ($array) must be of type array, null given
in 

/public_html/blog/wp-content/plugins/gp-auto-extract/gp-auto-extract.php on line 274
```

```
Call stack:

GP_Auto_Extract::extract_project()
wp-content/plugins/gp-auto-extract/gp-auto-extract.php:180
GP_Auto_Extract::auto_extract()
wp-content/plugins/glotpress/gp-includes/router.php:222
GP_Router::route()
wp-content/plugins/glotpress/gp-includes/rewrite.php:79
gp_run_route()
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:348
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-includes/template-loader.php:13
require_once()
wp-blog-header.php:19
require()
index.php:17``
```

**Comment by toolstack** [comment]
That looks like something is wrong with your project config, open a new issue and provide some of your config details (both for the project and the auto extract setup).
